Update run_after_05-configure-plow.sh.tmpl

diff --git a/HOME/dot_config/scripts/run_after_05-configure-plow.sh.tmpl b/HOME/dot_config/scripts/run_after_05-configure-plow.sh.tmpl
--- a/HOME/dot_config/scripts/run_after_05-configure-plow.sh.tmpl
+++ b/HOME/dot_config/scripts/run_after_05-configure-plow.sh.tmpl
@@ -205,10 +205,8 @@ echo -e "$ rm -f ~/.config/plasma-org.kde.plasma.desktop-appletsrc"
 rm -f "${HOME}/.config/plasma-org.kde.plasma.desktop-appletsrc"
 
 # Force regeneration by removing updates list
-echo -e "$ sed -i '/^\[Updates\]/,/^\[/{ /^\[Updates\]/d; /^\[/!d; }' ~/.config\
-/plasmashellrc 2>/dev/null || true"
-sed -i '/^\[Updates\]/,/^\[/{ /^\[Updates\]/d; /^\[/!d; }' "${HOME}/.config\
-/plasmashellrc" 2>/dev/null || true
+echo -e "$ sed -i '/^\[Updates\]/,/^\[/{ /^\[Updates\]/d; /^\[/!d; }' ~/.config/plasmashellrc 2>/dev/null || true"
+sed -i '/^\[Updates\]/,/^\[/{ /^\[Updates\]/d; /^\[/!d; }' "${HOME}/.config/plasmashellrc" 2>/dev/null || true
 
 # Quietly create directories if needed
 sudo mkdir -p "${TASKBAR_DIR}"
@@ -229,6 +227,7 @@ ENV_VARS_FILE="${ENV_VARS_DIR}/01-plasma-on-wslg.conf"
 
 ENV_VARS_TEXT="\
 # --- Driver / Hardware Layer ---
+DEB_HOST_MULTIARCH=$(dpkg-architecture -qDEB_HOST_MULTIARCH)
 LD_LIBRARY_PATH=/usr/lib/wsl/lib
 WSA_RENDER_DEVICE=/dev/dri/renderD128
 LIBVA_DRIVER_NAME=d3d12
@@ -450,6 +449,178 @@ echo -e "$ sudo install -CDm 644 ${source_dir}/index.theme ${target_dir}/index.t
 sudo install -CDm 644 "${source_dir}/index.theme" "${target_dir}/index.theme"
 
 # Close check for westonCursor theme
+fi
+
+# Build mesa from source
+
+echo -e "\n${cyanbold}Build mesa from source${normal}"
+echo -e "$ sudo apt build-dep mesa"
+sudo apt build-dep mesa
+echo -e "$ mkdir -p ${HOME}/git/mesa/mesa"
+mkdir -p "${HOME}/git/mesa/mesa"
+echo -e "$ cd ${HOME}/git/mesa/mesa"
+cd "${HOME}/git/mesa/mesa" 2> /dev/null \
+|| { echo -e "${redbold}> Failed to change directory, exiting${normal}"\
+; exit 101; }
+
+if [ ! -d "${HOME}/git/mesa/mesa/.git" ]; then
+echo -e "$ git clone --filter=blob:none --no-checkout https://gitlab.freedesktop.org/mesa/mesa.git ."
+git clone --filter=blob:none --no-checkout https://gitlab.freedesktop.org/mesa/mesa.git .
+fi
+
+echo -e "$ git fetch --tags origin"
+git fetch --tags origin
+
+MESA_TARGET="mesa-26.1"
+LATEST_VER=$(git tag -l "${MESA_TARGET}.*" --sort=-v:refname | grep -E "^${MESA_TARGET}\.[0-9]+$" | head -n 1)
+
+# Catch invalid MESA_TARGET
+if [ -z "${LATEST_VER}" ]; then
+echo -e "${redbold}> No valid release tag found for ${MESA_TARGET}, ending mesa build process${normal}"
+else
+
+VERSION_DIR="${HOME}/git/mesa/${LATEST_VER}"
+BUILD_DIR64="${VERSION_DIR}/builddir64"
+STAGE_DIR64="${VERSION_DIR}/mesa-wsl-64bit"
+BUILD_DIR32="${VERSION_DIR}/builddir32"
+STAGE_DIR32="${VERSION_DIR}/mesa-wsl-32bit"
+
+# Build each version only once
+if [ -d "${VERSION_DIR}" ]; then
+echo -e "${greenbold}> ${LATEST_VER} already built, ending mesa build process${normal}"
+else
+
+echo -e "$ git checkout ${LATEST_VER}"
+git checkout "${LATEST_VER}"
+
+echo -e "$ meson setup ${BUILD_DIR64} \
+-Dprefix=/usr \
+-Dlibdir=lib/${DEB_HOST_MULTIARCH} \
+-Dgallium-drivers=d3d12,swrast \
+-Dvulkan-drivers=microsoft-experimental \
+-Dgallium-nine=true \
+-Dgallium-va=enabled \
+-Dplatforms=wayland,x11 \
+-Dbuildtype=release \
+-Dstrip=true"
+meson setup "${BUILD_DIR64}" \
+-Dprefix=/usr \
+-Dlibdir="lib/${DEB_HOST_MULTIARCH}" \
+-Dgallium-drivers=d3d12,swrast \
+-Dvulkan-drivers=microsoft-experimental \
+-Dgallium-nine=true \
+-Dgallium-va=enabled \
+-Dplatforms=wayland,x11 \
+-Dbuildtype=release \
+-Dstrip=true
+
+echo -e "$ DESTDIR=${STAGE_DIR64} ninja -C ${BUILD_DIR64} install"
+DESTDIR="${STAGE_DIR64}" ninja -C "${BUILD_DIR64}" install
+
+echo -e "$ mkdir -p ${STAGE_DIR64}/DEBIAN"
+mkdir -p "${STAGE_DIR64}/DEBIAN"
+
+echo -e "> ${STAGE_DIR64}/DEBIAN/control"
+cat << EOF > "${STAGE_DIR64}/DEBIAN/control"
+Package: mesa-wsl2-64bit
+Version: ${LATEST_VER#mesa-}
+Architecture: amd64
+Maintainer: ${USER}
+Section: graphics
+Priority: optional
+Provides: libd3dadapter9-mesa, libegl-mesa0, libgl1-mesa-dri, libgl1-mesa-dev, libgles2-mesa-dev, libglx-mesa0, mesa-libgallium, mesa-va-drivers, mesa-vulkan-drivers, libglapi-mesa, vulkan-icd
+Replaces: libd3dadapter9-mesa, libegl-mesa0, libgl1-mesa-dri, libgl1-mesa-dev, libgles2-mesa-dev, libglx-mesa0, mesa-libgallium, mesa-va-drivers, mesa-vulkan-drivers, libglapi-mesa
+Conflicts: libd3dadapter9-mesa, libegl-mesa0, libgl1-mesa-dri, libgl1-mesa-dev, libgles2-mesa-dev, libglx-mesa0, mesa-libgallium, mesa-va-drivers, mesa-vulkan-drivers, libglapi-mesa
+Description: Custom 64-bit ${LATEST_VER} build optimised for WSL2
+ Provides core D3D12 drivers, and Gallium Nine
+EOF
+
+echo -e "$ dpkg-deb --build ${STAGE_DIR64} ${VERSION_DIR}/mesa-wsl2-64bit_${LATEST_VER#mesa-}.deb"
+dpkg-deb --build "${STAGE_DIR64}" "${VERSION_DIR}/mesa-wsl2-64bit_${LATEST_VER#mesa-}.deb"
+
+echo -e "$ sudo dpkg -i ${VERSION_DIR}/mesa-wsl2-64bit_${LATEST_VER#mesa-}.deb"
+sudo dpkg -i "${VERSION_DIR}/mesa-wsl2-64bit_${LATEST_VER#mesa-}.deb"
+
+CROSS_COMP_TEXT="\
+[binaries]
+c = 'gcc'
+cpp = 'g++'
+pkgconfig = 'i686-linux-gnu-pkg-config'
+[built-in options]
+c_args = ['-m32']
+c_link_args = ['-m32']
+cpp_args = ['-m32']
+cpp_link_args = ['-m32']
+[host_machine]
+system = 'linux'
+cpu_family = 'x86'
+cpu = 'i686'
+endian = 'little'
+"
+
+CROSS_COMP_DIR="${VERSION_DIR}"
+CROSS_COMP_FILE="${VERSION_DIR}/mesa-i386-cross.txt"
+
+# Configure cross-compilation file 
+if [ ! -s "${CROSS_COMP_FILE}" ] || \
+! cmp -s <(printf "%s" "${CROSS_COMP_TEXT}") "${CROSS_COMP_FILE}"; then
+echo -e "> ${VERSION_DIR}/mesa-i386-cross.txt"
+# Choosing to expand path but not file contents in echo output here
+# Hence backslash escapes for CROSS_COMP_TEXT variable
+echo -e "$ printf \"%s\" \"\${CROSS_COMP_TEXT}\" | tee ${CROSS_COMP_FILE} > \
+/dev/null"
+printf "%s" "${CROSS_COMP_TEXT}" | tee "${CROSS_COMP_FILE}" > /dev/null
+fi
+
+echo -e "$ meson setup ${BUILD_DIR32} \
+--cross-file ${CROSS_COMP_FILE} \
+-Dprefix=/usr \
+-Dlibdir=lib/i386-linux-gnu \
+-Dgallium-drivers=d3d12,swrast \
+-Dgallium-nine=true \
+-Dplatforms=x11 \
+-Dbuildtype=release \
+-Dstrip=true"
+meson setup "${BUILD_DIR32}" \
+--cross-file "${CROSS_COMP_FILE}" \
+-Dprefix=/usr \
+-Dlibdir=lib/i386-linux-gnu \
+-Dgallium-drivers=d3d12,swrast \
+-Dgallium-nine=true \
+-Dplatforms=x11 \
+-Dbuildtype=release \
+-Dstrip=true
+
+echo -e "$ DESTDIR=${STAGE_DIR32} ninja -C ${BUILD_DIR32} install"
+DESTDIR="${STAGE_DIR32}" ninja -C "${BUILD_DIR32}" install
+
+echo -e "$ mkdir -p ${STAGE_DIR32}/DEBIAN"
+mkdir -p "${STAGE_DIR32}/DEBIAN"
+
+echo -e "> ${STAGE_DIR32}/DEBIAN/control"
+cat << EOF > "${STAGE_DIR32}/DEBIAN/control"
+Package: mesa-wsl2-32bit
+Version: ${LATEST_VER#mesa-}
+Architecture: i386
+Maintainer: ${USER}
+Section: graphics
+Priority: optional
+Provides: libd3dadapter9-mesa
+Replaces: libd3dadapter9-mesa
+Conflicts: libd3dadapter9-mesa
+Description: Custom 32-bit ${LATEST_VER} build optimised for WSL2
+ Provides 32-bit Gallium Nine support for Wine applications.
+EOF
+
+echo -e "$ dpkg-deb --build ${STAGE_DIR32} ${VERSION_DIR}/mesa-wsl2-32bit_${LATEST_VER#mesa-}.deb"
+dpkg-deb --build "${STAGE_DIR32}" "${VERSION_DIR}/mesa-wsl2-32bit_${LATEST_VER#mesa-}.deb"
+
+echo -e "$ sudo dpkg -i ${VERSION_DIR}/mesa-wsl2-32bit_${LATEST_VER#mesa-}.deb"
+sudo dpkg -i "${VERSION_DIR}/mesa-wsl2-32bit_${LATEST_VER#mesa-}.deb"
+
+# End of catch invalid MESA_TARGET
+fi
+# End of build each version only once
 fi
 
 # Check WSL kernel version
